service: weather-cache

runtime: go121

instance_class: B1

main: ./cmd

basic_scaling:
  max_instances: 4
  idle_timeout: 3m

handlers:
  - url: /.*
    script: auto
    secure: always
    redirect_http_response_code: 301
