name: Update Weather
on:
  workflow_dispatch:
  schedule:
    #         ┌───────────── minute (0 - 59)
    #         │  ┌───────────── hour (0 - 23) CST is -5 UTC
    #         │  │ ┌───────────── day of the month (1 - 31)
    #         │  │ │ ┌───────────── month (1 - 12 or JAN-DEC)
    #         │  │ │ │ ┌───────────── day of the week (0 - 6 or SUN-SAT)
    #         │  │ │ │ │
    #         │  │ │ │ │
    #         │  │ │ │ │
    #         *  * * * *
    - cron: "*/30 * * * *" # Every 30 min https://crontab.guru/
jobs:
  trigger-update:
    permissions:
      contents: "read"
      id-token: "write"

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - id: "auth"
        uses: "google-github-actions/auth@v0"
        with:
          credentials_json: "${{ secrets.GCP_SA_CREDS_JSON }}"

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v0"

      # Using curl over "gcloud functions call" to specify the /notify endpoint
      - id: "make-request"
        run: >
          curl
          --fail
          -X POST
          -H "Authorization: bearer $(gcloud auth print-identity-token)"
          -H 'Content-Type: application/json'
          -d '{}'
          https://weather-cache-vznq5rz67q-uc.a.run.app
